application: medi-map
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
- url: .*
  script: medimap.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
